version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - USE_MINIO=true
      - OUTPUT_BASE=s3a://sms-reports
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS=minio
      - MINIO_SECRET=minio123
      - INPUT_DIR=/opt/spark-data/REF_SMS_streaming
      - REF_MAP_PATH=/opt/spark-data/REF_map/ref.csv
    ports:
      - "8080:8080"
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/opt/spark-data
    depends_on:
      - minio

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ./data:/opt/spark-data
    depends_on:
      - spark-master

volumes:
  minio_data:
